FROM python:{{BASE_IMAGE_VERSION}}-slim-buster

LABEL maintainer="Maxime Sibellas <maxime.sibellas@ekino.com>"

ARG TERRAFORM_VERSION
ARG AZURE_CLI

RUN apt-get update -qq && apt-get install -qq -y ca-certificates curl apt-transport-https gcc wget unzip \
    && pip install azure-cli==${AZURE_CLI} \
    && wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip \
    && unzip -o terraform.zip \
    && mv terraform /usr/bin/ \
    && chmod +x /usr/bin/terraform\
    && rm terraform.zip \
    && apt-get remove -y unzip gcc && apt-get -qq -y autoremove \
    && apt-get -qq -y clean && apt-get -y -qq purge\
    && rm -rf /var/lib/apt/lists/* /var/lib/dpkg/*-old
