FROM golang:{{BASE_IMAGE_VERSION}}
LABEL maintainer="Raphaël Benitte <raphael.benitte@ekino.com>"

ARG CI_HELPER_VERSION

RUN echo "Starting...\n" && \

  echo "Installing AWS CLI..." && \
  apt-get update -q && \
  apt-get -qq -y install python-pip groff-base && \
  pip install -q -U awscli && \
  echo "Successfully installed AWS CLI\n" && \

  echo "Installing CI Helper..." && \
  curl -sSL https://github.com/rande/gitlab-ci-helper/releases/download/${CI_HELPER_VERSION}/linux-amd64-gitlab-ci-helper -o /usr/bin/ci-helper && \
  chmod 755 /usr/bin/ci-helper && \
  echo "Successfully installed CI Helper\n" && \

  echo "Adding an up to date mime-types definition file" && \
  curl -sSL https://salsa.debian.org/debian/mime-support/raw/master/mime.types -o /etc/mime.types && \

  echo "Done!"
