versions:
  "2":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
      NODE_VERSION: 12.13.0
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - node --version
        - npm --version
        - modd --version
        - react-native --version
        - rnpm --version
        - yarn --version
