versions:
  "8.1":
    platforms:
      - linux/amd64
      - linux/arm64
    github_versions:
      SONARSCANNER_VERSION:
        repo: SonarSource/sonar-scanner-cli
        rule: highest_with_prefix
    test_config:
      cmd:
        - java -version
        - sonar-scanner -v
