versions:
  "6.2":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config:
      cmd:
        - java -version
        - sonar-scanner -v
        - output$(sonar-scanner -v) && echo $output | grep "SonarScanner CLI 6.2"
