FROM python:{{ BASE_IMAGE_VERSION }}-slim-buster
LABEL maintainer="Loïc Nairi <loic.nairi@ekino.com>"

ARG SERVERLESS_VERSION
ARG YARN_VERSION
ENV PATH="$PATH:/opt/yarn-v${YARN_VERSION}/bin"

RUN echo "Starting ..." && \
    apt-get update -qq && \
    apt-get install -qq -y curl && \
    echo "Install system dependencies for node" && \
    curl -sL https://deb.nodesource.com/setup_13.x | bash - && \
    apt-get install -y nodejs wget tar gzip && \
    cd /opt && wget https://github.com/yarnpkg/yarn/releases/download/v1.22.0/yarn-v${YARN_VERSION}.tar.gz && tar zvxf yarn-v${YARN_VERSION}.tar.gz && \
    echo "Done base install!" && \
    echo "Install basics Python tools" && \
    pip install -U pip && \
    pip install pipenv awscli boto3 && \
    echo "Done basic python tools install" && \
    echo "Install serverless" && \
    npm config set unsafe-perm true && \
    npm install -g serverless@${SERVERLESS_VERSION} && \
    npm install -g serverless-python-requirements && \
    echo "Done serverless install" && \
    echo "Cleaning files!" && \
    echo "Done!"
