versions:
  "5.7":
    build_args:
      SCOUTSUITE_VERSION: 5.7.0
    test_config:
      cmd:
        - pip --version
        - pipenv --version
        - scout --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8
