test_config: &test_config
  cmd:
    - pip --version
    - python --version
    - node --version
    - npm --version
    - aws --version

versions:
  "3.8":
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 3.8
  "3.7":
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 3.7
