versions:
  "1":
    test_config:
      cmd:
        - aws --version
        - git --version
        - helm diff version
        - helm version
        - kustomize version
        - pip --version
        - pipenv --version
        - trivy --version
        - zip --version
        - terragrunt --version
        - infracost --version
        - tfenv init
        - kubectl version --client
