FROM python:{{ BASE_IMAGE_VERSION }}-slim-buster
LABEL maintainer="Frank Pavageau <fpavageau@ekino.com>"

RUN echo "Install AWS" && \
    apt-get update -qq && apt-get install -qq -y curl git && \
    pip install -U pip && \
    pip install pipenv awscli boto3 awsebcli PyYAML && \
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb" && \
    dpkg -i session-manager-plugin.deb && session-manager-plugin && \
    curl -L "https://github.com/danmx/sigil/releases/download/{{ SIGIL_VERSION }}/sigil_linux-amd64.tar.gz" -o sigil_linux-amd64.tar.gz && \
    tar xzf sigil_linux-amd64.tar.gz && \
    cp sigil /usr/local/bin && \
    echo "Done install AWS" && \
    apt-get -qq -y autoremove && \
    apt-get -qq clean && apt-get -qq purge && \
    rm -rf /var/lib/apt/lists/* /var/lib/dpkg/*-old && \
    echo "Adding an up to date mime-types definition file" && \
    curl -sSL https://salsa.debian.org/debian/mime-support/raw/master/mime.types -o /etc/mime.types
