versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    github_versions:
      COSIGN_VERSION: sigstore/cosign
      CRANE_VERSION: google/go-containerregistry
      SYFT_VERSION: anchore/syft
      TRIVY_VERSION: aquasecurity/trivy
    test_config:
      cmd:
        - aws --version
        - az version
        - docker --version
        - docker-compose --version
        - task --version
        - trivy --version
        - cosign version
        - crane version
        - syft version
