FROM golang:{{ BASE_IMAGE_VERSION }}-buster

LABEL maintainer="Maxime Sibellas <maxime.sibellas@ekino.com>"

ARG TERRAFORM_VERSION
ARG IBM_PROVIDER_VERSION
ARG IBM_CLI_VERSION
ARG IBM_NULL_PROVIDER_VERSION
ARG AWS_PROVIDER_VERSION
ARG KUBERNETES_PROVIDER_VERSION
ARG KUBECTL_VERSION
ARG KUBEVAL_VERSION
ARG KUSTOMIZATION_VERSION
ARG HELM_VERSION

RUN apt-get update -qq \
    && apt-get -y -qq install wget unzip make \
    && echo "Install IBMCloud CLI" \
    && wget https://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/${IBM_CLI_VERSION}/binaries/IBM_Cloud_CLI_${IBM_CLI_VERSION}_linux_amd64.tgz \
    && tar -xzf IBM_Cloud_CLI_${IBM_CLI_VERSION}_linux_amd64.tgz  -C /usr/local/bin --strip-components 1 IBM_Cloud_CLI/ibmcloud \
    && rm -rf IBM_Cloud_CLI_${IBM_CLI_VERSION}_linux_amd64.tgz \
    && ibmcloud plugin install vpc-infrastructure \
    && ibmcloud plugin install kubernetes-service \
    && ibmcloud plugin install container-registry \
    && ibmcloud plugin install cloud-databases \
    && ibmcloud plugin install functions \
    && ibmcloud cf install

RUN echo "Install Terraform" \
    && wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip \
    && unzip terraform.zip -d /usr/bin/ \
    && rm terraform.zip \
    && chmod +x /usr/bin/terraform

RUN echo "Install IBM Terraform providers" \
    && wget https://github.com/IBM-Cloud/terraform-provider-ibm/releases/download/v${IBM_PROVIDER_VERSION}/linux_amd64.zip \
    && mkdir -p /terraform.d/plugins \
    && unzip linux_amd64.zip -d /terraform.d/plugins \
    && rm linux_amd64.zip

RUN echo "Install Null Terraform providers" \
    && wget https://github.com/hashicorp/terraform-provider-null/archive/v${IBM_NULL_PROVIDER_VERSION}.zip \
    && unzip v${IBM_NULL_PROVIDER_VERSION}.zip && rm v${IBM_NULL_PROVIDER_VERSION}.zip \
    && cd terraform-provider-null-${IBM_NULL_PROVIDER_VERSION} \
    && make build \
    && mv $GOPATH/bin/terraform-provider-null /terraform.d/plugins/terraform-provider-null_v${IBM_NULL_PROVIDER_VERSION}

RUN echo "Install AWS Terraform providers" \
    && wget https://github.com/terraform-providers/terraform-provider-aws/archive/v${AWS_PROVIDER_VERSION}.zip \
    && unzip v${AWS_PROVIDER_VERSION}.zip && rm v${AWS_PROVIDER_VERSION}.zip \
    && cd terraform-provider-aws-${AWS_PROVIDER_VERSION} \
    && make build \
    && mv $GOPATH/bin/terraform-provider-aws /terraform.d/plugins/terraform-provider-aws_v${AWS_PROVIDER_VERSION}

RUN echo "Install Kuberenetes Terraform providers" \
    && wget https://github.com/terraform-providers/terraform-provider-kubernetes/releases/download/v${KUBERNETES_PROVIDER_VERSION}/terraform-provider-kubernetes_${KUBERNETES_PROVIDER_VERSION}_linux_amd64.zip \
    && unzip terraform-provider-kubernetes_${KUBERNETES_PROVIDER_VERSION}_linux_amd64.zip -d /terraform.d/plugins \
    && rm terraform-provider-kubernetes_${KUBERNETES_PROVIDER_VERSION}_linux_amd64.zip

RUN echo "Install kubectl, helm and kubernetes related clis" \
    && curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl && mv ./kubectl /usr/bin/kubectl

RUN wget https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
    && tar xf helm-v${HELM_VERSION}-linux-amd64.tar.gz && rm helm-v${HELM_VERSION}-linux-amd64.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm

RUN wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZATION_VERSION}/kustomize_v${KUSTOMIZATION_VERSION}_linux_amd64.tar.gz \
    && tar -xf kustomize_v${KUSTOMIZATION_VERSION}_linux_amd64.tar.gz \
    && mv ./kustomize /usr/bin/kustomize

RUN wget https://github.com/instrumenta/kubeval/releases/download/${KUBEVAL_VERSION}/kubeval-linux-amd64.tar.gz \
    && tar -xf kubeval-linux-amd64.tar.gz \
    && mv kubeval /usr/local/bin/kubeval
