test_config: &test_config
  cmd:
    - python --version
    - pip --version
    - ansible --version
    - ansible-playbook --version

versions:
  "2.9":
    template_vars:
      BASE_IMAGE_VERSION: 3.8
    build_args:
      ANSIBLE_VERSION: 2.9.5
    test_config: *test_config
