versions:
  "2.9":
    build_args:
      ANSIBLE_VERSION: 2.9.10
    test_config:
      cmd:
        - python --version
        - pip --version
        - ansible --version
        - ansible-playbook --version
        - echo "foo"
