versions:
  '1':
    platforms:
      - linux/amd64
      - linux/arm64
    github_versions:
      HELM_DIFF_VERSION: databus23/helm-diff
      HELM_VERSION:
        repo: helm/helm
        rule: latest_v3
      INFRACOST_VERSION: infracost/infracost
      KUSTOMIZE_VERSION:
        repo: kubernetes-sigs/kustomize
        rule: kustomize
      TERRAGRUNT_VERSION: gruntwork-io/terragrunt
      TRIVY_VERSION: aquasecurity/trivy
    test_config:
      cmd:
        - gcloud --version
        - git --version
        - helm diff version
        - helm version
        - kustomize version
        - pip --version
        - pipenv --version
        - zip --version
        - unzip -v
        - trivy --version
        - terragrunt --version
        - infracost --version
        - tfenv init
        - kubectl version --client
